version: "3.8"
services:
  app:
    image: henryenoch22/patitasalrescate:1.0.0
      #context: .
      #dockerfile: Dockerfile
    container_name: patitasalrescate
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo


  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password

volumes:
  mongo-data:
  